version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "semantic-content-fs"
resolve_s3 = true
region = "af-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
